---
- name: Aplicar parches de Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Instalar todas las actualizaciones disponibles
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
