---
- name: Parchear servidor Windows
  hosts: trendmicropruebas
  gather_facts: no
  tasks:
    - name: Instalar todas las actualizaciones disponibles
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
