- name: Validación y mantenimiento en servidor Windows
  hosts: trendmicropruebas
  gather_facts: yes

  tasks:
    - name: Mostrar información del sistema
      debug:
        var: ansible_facts

    - name: Ejecutar liberador de espacio en disco (Cleanmgr)
      win_command: cleanmgr /sagerun:1
      register: cleanmgr_result
      ignore_errors: true

    - name: Mostrar resultado de cleanmgr
      debug:
        var: cleanmgr_result.stdout_lines

    - name: Ejecutar script de PowerShell personalizado
      win_shell: |
        Write-Host "→ Iniciando validación del sistema..."
        Get-ComputerInfo | Select-Object OSName, OSVersion, CsTotalPhysicalMemory
        Write-Host "`nTop 5 procesos por uso de CPU:"
        Get-Process | Sort-Object CPU -Descending | Select-Object Name, CPU -First 5
        Write-Host "`nÚltimos 5 eventos del log del sistema:"
        Get-EventLog -LogName System -Newest 5 | Select-Object TimeGenerated, EntryType, Source, EventID, Message
      register: powershell_output

    - name: Mostrar resultado del script de PowerShell
      debug:
        var: powershell_output.stdout_lines
