---
- name: Desinstalar Zabbix en Linux (con búsqueda y limpieza de carpetas)
  hosts: linux
  gather_facts: true
  become: true

  vars:
    zabbix_pkg_candidates:
      - zabbix-agent
      - zabbix-agent2
    zabbix_common_paths:
      - /etc
      - /var
      - /usr/local
      - /opt
      - /home

  tasks:
    - name: Detener servicios Zabbix (si existen)
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
      loop:
        - zabbix-agent
        - zabbix-agent2
      ignore_errors: true

    - name: Desinstalar paquetes Zabbix con gestor nativo
      ansible.builtin.package:
        name: "{{ zabbix_pkg_candidates }}"
        state: absent
      ignore_errors: true

    # Limpieza directa de rutas más comunes
    - name: Eliminar carpeta config /etc/zabbix si existe
      ansible.builtin.file:
        path: /etc/zabbix
        state: absent
      ignore_errors: true

    - name: Eliminar carpeta datos /var/lib/zabbix si existe
      ansible.builtin.file:
        path: /var/lib/zabbix
        state: absent
      ignore_errors: true

    - name: Eliminar carpeta logs /var/log/zabbix si existe
      ansible.builtin.file:
        path: /var/log/zabbix
        state: absent
      ignore_errors: true

    # Búsqueda de carpetas "zabbix" en rutas comunes (fallback)
    - name: Buscar carpetas llamadas 'zabbix' en rutas comunes
      ansible.builtin.find:
        paths: "{{ item }}"
        file_type: directory
        patterns: "zabbix"
        recurse: true
        follow: false
      loop: "{{ zabbix_common_paths }}"
      register: zabbix_dirs_found
      failed_when: false
      changed_when: false

    - name: Consolidar rutas encontradas
      ansible.builtin.set_fact:
        zabbix_dirs_all: "{{ (zabbix_dirs_all | default([])) + (item.files | map(attribute='path') | list) }}"
      loop: "{{ zabbix_dirs_found.results | default([]) }}"
      when: item.matched | default(0) | int > 0

    - name: Eliminar todas las carpetas 'zabbix' encontradas
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ zabbix_dirs_all | default([]) }}"
      when: (zabbix_dirs_all | default([])) | length > 0
      ignore_errors: true

    - name: Aviso si no se encontró ninguna carpeta 'zabbix' extra
      ansible.builtin.debug:
        msg: "No se encontraron carpetas adicionales llamadas 'zabbix' fuera de las rutas comunes."
      when: (zabbix_dirs_all | default([])) | length == 0
