---
- name: Desinstalar Zabbix en Linux (con soporte de llave SSH desde Encuesta)
  hosts: a_desinstalar_zabbix_linux
  gather_facts: true
  become: true

  vars:
    # Variables desde la encuesta
    ansible_user: "{{ usuario_ssh }}"
    ansible_port: "{{ puerto_ssh | default(22) }}"
    ansible_ssh_private_key_file: "/tmp/ansible_key_{{ inventory_hostname }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  pre_tasks:
    - name: Guardar llave SSH temporal para este host
      copy:
        content: "{{ llave_ssh }}"
        dest: "/tmp/ansible_key_{{ inventory_hostname }}"
        mode: '0600'
      no_log: true

  tasks:
    - name: Desinstalar Zabbix en Debian/Ubuntu
      apt:
        name: zabbix-agent
        state: absent
      when: ansible_facts['os_family'] == "Debian"

    - name: Desinstalar Zabbix en RedHat/CentOS
      yum:
        name: zabbix-agent
        state: absent
      when: ansible_facts['os_family'] == "RedHat"

    - name: Verificar que el servicio Zabbix ya no exista
      service_facts:

    - name: Confirmar eliminación de servicio Zabbix
      debug:
        msg: "Servicio Zabbix aún presente en {{ inventory_hostname }}"
      when: "'zabbix-agent' in services"

  post_tasks:
    - name: Borrar llave temporal
      file:
        path: "/tmp/ansible_key_{{ inventory_hostname }}"
        state: absent
      no_log: true
