---
- name: Desinstalar Zabbix en Windows (con búsqueda y limpieza de carpetas)
  hosts: windows
  gather_facts: false

  tasks:
    - name: Detener servicios Zabbix si existen
      ansible.windows.win_service:
        name: "{{ item }}"
        state: stopped
      loop:
        - "Zabbix Agent"
        - "Zabbix Agent 2"
      ignore_errors: true

    - name: Desinstalar 'Zabbix Agent'
      ansible.windows.win_package:
        name: "Zabbix Agent"
        state: absent
      ignore_errors: true

    - name: Desinstalar 'Zabbix Agent 2'
      ansible.windows.win_package:
        name: "Zabbix Agent 2"
        state: absent
      ignore_errors: true

    - name: Eliminar carpeta C:\czabbix si existe
      ansible.windows.win_file:
        path: "C:\\czabbix"
        state: absent
      ignore_errors: true

    - name: "Buscar carpeta 'czabbix' en todo C:"   # <- ¡citado!
      ansible.windows.win_shell: |
        Get-ChildItem -Path C:\ -Directory -Filter "czabbix" -Recurse -ErrorAction SilentlyContinue |
        Select-Object -ExpandProperty FullName
      register: czabbix_dirs
      changed_when: false
      failed_when: false

    - name: Eliminar carpetas 'czabbix' encontradas
      ansible.windows.win_file:
        path: "{{ item }}"
        state: absent
      loop: "{{ (czabbix_dirs.stdout_lines | default([])) | unique }}"
      when: (czabbix_dirs.stdout_lines | default([])) | length > 0
      ignore_errors: true

    - name: Aviso si no se encontró ninguna carpeta 'czabbix' extra
      ansible.builtin.debug:
        msg: "No se encontraron carpetas adicionales llamadas 'czabbix'."
      when: (czabbix_dirs.stdout_lines | default([])) | length == 0
