---
- name: Validación y desinstalación de Zabbix (con llave SSH desde Encuesta)
  hosts: linux
  gather_facts: true
  become: true

  vars:
    # Variables desde la Encuesta
    usuario_ssh: "{{ usuario_ssh }}"
    llave_ssh: "{{ llave_ssh }}"
    puerto_ssh: "{{ puerto_ssh | default(22) }}"

    ansible_user: "{{ usuario_ssh }}"
    ansible_port: "{{ puerto_ssh }}"
    ansible_ssh_private_key_file: "/tmp/ansible_key_{{ inventory_hostname }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  pre_tasks:
    - name: Guardar llave SSH temporal para este host
      copy:
        content: "{{ llave_ssh }}"
        dest: "/tmp/ansible_key_{{ inventory_hostname }}"
        mode: '0600'
      no_log: true

  tasks:
    - name: Verificar uptime
      command: uptime

    - name: Mostrar información del sistema
      setup:
        gather_subset:
          - hardware
          - network
          - virtual

    - name: Desinstalar Zabbix (Debian/Ubuntu)
      apt:
        name: zabbix-agent
        state: absent
      when: ansible_facts['os_family'] == "Debian"

    - name: Desinstalar Zabbix (RedHat/CentOS)
      yum:
        name: zabbix-agent
        state: absent
      when: ansible_facts['os_family'] == "RedHat"

    - name: Verificar que el servicio Zabbix ya no exista
      service_facts:

    - name: Confirmar eliminación de servicio Zabbix
      debug:
        msg: "Servicio Zabbix aún presente en {{ inventory_hostname }}"
      when: "'zabbix-agent' in services"

  post_tasks:
    - name: Borrar llave temporal
      file:
        path: "/tmp/ansible_key_{{ inventory_hostname }}"
        state: absent
      no_log: true
