---
- name: Desinstalar Zabbix en Windows (con búsqueda y limpieza de carpetas)
  hosts: windows
  gather_facts: false

  vars:
    # Raíces donde buscar para evitar un recurse de todo el disco con excesivo costo
    search_roots:
      - "C:\\"
      - "$env:ProgramFiles"
      - "$env:ProgramFiles(x86)"
      - "$env:ProgramData"
      - "$env:SystemDrive\\Users"

  tasks:
    - name: Detener servicios Zabbix si existen
      ansible.windows.win_service:
        name: "{{ item }}"
        state: stopped
      loop:
        - "Zabbix Agent"
        - "Zabbix Agent 2"
      ignore_errors: true

    - name: Desinstalar 'Zabbix Agent' (si está instalado)
      ansible.windows.win_package:
        name: "Zabbix Agent"
        state: absent
      ignore_errors: true

    - name: Desinstalar 'Zabbix Agent 2' (si está instalado)
      ansible.windows.win_package:
        name: "Zabbix Agent 2"
        state: absent
      ignore_errors: true

    # Limpieza directa por si quedó una ruta conocida
    - name: Eliminar carpeta C:\czabbix si existe
      ansible.windows.win_file:
        path: "C:\\czabbix"
        state: absent
      ignore_errors: true

    # Búsqueda de carpetas llamadas "czabbix" (fallback)
    - name: Buscar carpetas llamadas 'czabbix' en rutas comunes (PowerShell)
      ansible.windows.win_shell: |
        $roots = @( {{ search_roots | map('regex_replace', '^', '"') | map('regex_replace', '$', '"') | join(', ') }} )
        $results = @()
        foreach ($r in $roots) {
          try {
            if ($r -match '^\$') { $r = Invoke-Expression $r }
            if (-not [string]::IsNullOrWhiteSpace($r) -and (Test-Path $r)) {
              Get-ChildItem -Path $r -Directory -Filter "czabbix" -Recurse -ErrorAction SilentlyContinue |
                Select-Object -ExpandProperty FullName | ForEach-Object { $results += $_ }
            }
          } catch { }
        }
        $results | Sort-Object -Unique
      register: czabbix_dirs
      changed_when: false
      failed_when: false

    - name: Eliminar todas las carpetas 'czabbix' encontradas
      ansible.windows.win_file:
        path: "{{ item }}"
        state: absent
      loop: "{{ (czabbix_dirs.stdout_lines | default([])) | unique }}"
      when: (czabbix_dirs.stdout_lines | default([])) | length > 0
      ignore_errors: true

    - name: Aviso si no se encontró ninguna carpeta 'czabbix' extra
      ansible.builtin.debug:
        msg: "No se encontraron carpetas adicionales llamadas 'czabbix' fuera de C:\\czabbix."
      when: (czabbix_dirs.stdout_lines | default([])) | length == 0
