---
- name: Validaci贸n de servidor Windows
  hosts: all
  gather_facts: no
  tasks:

    - name: Obtener ruta del escritorio
      win_shell: |
        [Environment]::GetFolderPath("Desktop")
      register: desktop_path_raw

    - name: Limpiar ruta del escritorio
      set_fact:
        desktop_path: "{{ desktop_path_raw.stdout | trim }}"

    - name: Crear carpeta LogsAnsible en el escritorio si no existe
      win_file:
        path: "{{ desktop_path }}\\LogsAnsible"
        state: directory

    - name: Verificar estado de servicios (sin m贸dulo ansible.windows)
      win_shell: |
        Get-Service | Select-Object Name, DisplayName, Status, StartType |
          ConvertTo-Json -Depth 2
      register: service_info   

    - name: Verificar espacio en disco
      win_shell: |
        Get-PSDrive -PSProvider FileSystem | Select-Object Name,Free,Used, @{Name="TotalGB";Expression={[math]::round($_.Used/1GB + $_.Free/1GB, 2)}} | ConvertTo-Json
      register: disk_info

    - name: Crear log de validaci贸n en texto plano
      win_copy:
        content: |
          ==== Validaci贸n de Servidor Windows ====
          Servicios:
          {{ service_info.stdout }}

          Espacio en disco:
          {{ disk_info.stdout }}
        dest: "{{ desktop_path }}\\LogsAnsible\\validacion_windows.txt"

