- name: Validación de servidor Windows
  hosts: all
  gather_facts: false
  tasks:

    - name: Obtener ruta del escritorio
      win_shell: |
        [System.Environment]::GetFolderPath('Desktop')
      register: escritorio

    - name: Crear carpeta LogsAnsible en el escritorio si no existe
      win_file:
        path: "{{ escritorio.stdout }}\\LogsAnsible"
        state: directory

    - name: Obtener información del sistema
      win_shell: systeminfo
      register: sistema

    - name: Obtener espacio en disco
      win_shell: Get-PSDrive C | Select-Object Used,Free,Name
      register: espacio_disco

    - name: Obtener servicios activos
      win_shell: Get-Service | Where-Object {$_.Status -eq "Running"}
      register: servicios_det

    - name: Generar archivo de log en el escritorio
      copy:
        dest: "{{ escritorio.stdout }}\\LogsAnsible\\validacion_log.txt"
        content: |
          --- VALIDACIÓN DE SISTEMA WINDOWS ---
          Fecha: {{ ansible_date_time.date }} {{ ansible_date_time.time }}

          --- Información del sistema ---
          {{ sistema.stdout }}

          --- Espacio en disco ---
          {{ espacio_disco.stdout }}

          --- Servicios en ejecución ---
          {{ servicios_det.stdout }}

        force: true
